# Generated by Django 4.0.4 on 2022-05-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_remove_offer_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
