# Generated by Django 4.0.4 on 2022-05-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_alter_offer_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['amount']},
        ),
    ]
