# Generated by Django 4.0.4 on 2022-05-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_alter_offer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={},
        ),
    ]
