# Generated by Django 4.0.4 on 2022-05-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_alter_offer_amount'),
        ('checkout', '0002_country_alter_paymentinfo_cvc_contactinfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offer.offer'),
            preserve_default=False,
        ),
    ]
