# Generated by Django 4.0.4 on 2022-05-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_country_alter_paymentinfo_cvc_contactinfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='cool_meter',
            field=models.CharField(default=1, max_length=999),
        ),
    ]
