# Generated by Django 4.0.4 on 2022-05-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_paymentinfo_cool_meter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='cool_meter',
        ),
    ]
