# Generated by Django 4.0.4 on 2022-05-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_purchase_offer'),
        ('checkout', '0004_remove_paymentinfo_cool_meter'),
    ]

    operations = [
    ]
