# Generated by Django 4.0.4 on 2022-05-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_message_recipient_alter_userprofile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='offer_accepted',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='offer_declined',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='offer_received',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='push_notification',
        ),
    ]
