# Generated by Django 4.0.4 on 2022-05-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_usersettings_offer_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='email_notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(default='', max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersettings',
            name='temporary',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('purchase',), name='one rating per purchase'),
        ),
    ]
